version: "3"
services:
  app:
    build: .
    links:
      - db
    container_name: app
    ports:
      - "8080:8080"
  db:
    image: mysql:5.7
    container_name: mysql_server_container
    ports:
      - "32000:3306"
    volumes:
      - /var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always
    environment:
        MYSQL_ROOT_PASSWORD: admin
        MYSQL_DATABASE: orders
        MYSQL_USER: admin
        MYSQL_PASSWORD: admin



